# Generated by Django 4.2 on 2023-04-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='rentalrate',
            name='vehicle_size',
        ),
        migrations.RemoveField(
            model_name='rentalrate',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='size',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.DeleteModel(
            name='RentalRate',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleSize',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
