-- left join -- right join
-- select title, name
-- from film as f
-- right join language as l
-- on
-- f.language_id = l.language_id;

-- check without intersection
-- select title, name
-- from film as f
-- full join language as l
-- on
-- f.language_id = l.language_id
-- where title is Null or name is Null
-- ;