# Generated by Django 4.2 on 2023-05-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0003_gif_likes_alter_category_gifs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gif',
            name='likes',
        ),
    ]
