# Generated by Django 4.2 on 2023-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0004_remove_gif_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='gif',
            name='uploader_name',
            field=models.CharField(max_length=150),
        ),
    ]
